### ISSUE TITLE
Space is added to browser name when IE

### ISSUE THREAD

**Issue by johansuperstar** [stevelacy/browser-info#1]
Used this module to retrieve browser info and found that there was a space added to the browser name when IE.

Checked the code and found at line 29 in index.js (https://github.com/stevelacy/browser-info/blob/master/index.js#L29) there is a space added. 

Is there any reason for this or is it a typo?

**Comment by stevelacy** [comment]
good catch, I don't remember any reason for it.

want to PR?

**Comment by johansuperstar** [comment]
Created a pull request for the fix

**Comment by stevelacy** [comment]
merged, publishing.

thanks
