### ISSUE TITLE
Wrong result with tricky UA

### ISSUE THREAD

**Issue by nicolas-goudry** [stevelacy/browser-info#12]
Hello,

Thanks for this package!

I found a bug, with following UA:

`Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.116 Safari/537.36 Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B334b Safari/531.21.10`

This one is tricky but is actually a real one! Chrome 34 on XP, I don't know why there is iPad mentioned, neither Safari…

The actual output is Chrome 4 on iOS, so that's not right I guess :smile: 

It's not very relevant to inspect the UA but I understand that in most cases it does the job.

Do you think it can be fixed?

Thanks!

**Comment by stevelacy** [comment]
Interesting... (thanks google)
The correct system is `Chrome/34` though all the other browser placeholders are added. 

I have just published `0.5.0` with support for cascading info - thus the version would be taken from `Chrome/[version]` before it is taken from `Version/[version]`

Let me know if this Breaks anything else.....
I also added tests for ensuring that the versions taken from the user agents are correct.

**Comment by nicolas-goudry** [comment]
Ok fine, I will digg into it soon!

Thanks for the quick reply :smile:

**Comment by stevelacy** [comment]
Did the update solve your issue? @nicolas-goudry

**Comment by nicolas-goudry** [comment]
Just tested and it looks good for all properties except OS:

```javascript
Object {name: "Chrome", version: "34", fullVersion: "34.0.1847.116", os: "iOS"}
```

**Comment by stevelacy** [comment]
Can you try now?
