### ISSUE TITLE
Crashes with Postman

### ISSUE THREAD

**Issue by mariorodriguespt** [stevelacy/browser-info#19]
The following user-agent crashes `PostmanRuntime/7.2.0`
Postman version `Version 6.2.5 (6.2.5)`
Os `macOS Sierra 10.12.6`

It would be nice to support this user-agent (also others), since postman and other tools are heavily used during development.

**Comment by stevelacy** [comment]
What is the error?

**Comment by mariorodriguespt** [comment]
Node crashes and print this message along with a stack trace.

> (node:55768) UnhandledPromiseRejectionWarning: ReferenceError: navigator is not defined

**Comment by stevelacy** [comment]
Ah, not an issue with postman, this will not work in node. It is browser only.

**Comment by stevelacy** [comment]
On node add a navigator type before using the browserInfo function:
```js
    global.navigator = {
      userAgent: 'Nodejs',
      appName: 'Node',
      appVersion: '9.0'
    };

```
