### ISSUE TITLE
Detecting the new Microsoft Edge as Chrome

### ISSUE THREAD

**Issue by csk1827** [stevelacy/browser-info#21]
When I try to use the library to detect the new Microsoft Edge browser, it is detecting the browser as Chrome. Microsoft changed the name from Edge to Edg as shown in the UserAgent field of the request:

`User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36 Edg/80.0.361.109`

@stevelacy I worked on the changes need to be done for accommodating this update. Can you please check it out? We want it to be updated ASAP, as we are using this library and getting the wrong information.

**Comment by stephenlacy** [comment]
merged and published as 1.3.0

**Comment by csk1827** [comment]
@stevelacy thank you very much!
