### ISSUE TITLE
Return OS version

### ISSUE THREAD

**Issue by vadimdemedes** [stevelacy/browser-info#4]
Hey, would be nice if this module returned not only browser version, but OS version as well.

Example ua string:

> Mozilla/5.0 (Macintosh; Intel Mac OS X **10_11_3**) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36

Coming from: https://github.com/vdemedes/env-info/issues/2

Thanks!

**Comment by stevelacy** [comment]
PR?
